
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Intelligence.Client
{
  public partial class IntelligenceModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("e08dc659-2828-4d50-b90d-7d06408ab7cb"); }
    }

    public override string Name
    {
      get { return "Sungero.Intelligence"; }
    }

    public override void RegisterTypes()
    {



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.Intelligence.Client.IModuleClientPublicFunctions, global::Sungero.Intelligence.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.Intelligence.Shared.IModuleSharedPublicFunctions, global::Sungero.Intelligence.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
