
// ==================================================================
// VATRateState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Shared
{
  public class VATRateState : 
    global::Sungero.CoreEntities.Shared.DatabookEntryState, global::Sungero.Commons.IVATRateState
  {
    public VATRateState(global::Sungero.Commons.IVATRate entity) : base(entity) { }

    public new global::Sungero.Commons.IVATRatePropertyStates Properties
    {
      get { return (global::Sungero.Commons.IVATRatePropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Commons.Shared.VATRatePropertyStates(entity);
    }


    public new global::Sungero.Commons.IVATRateControlStates Controls
    {
      get { return (global::Sungero.Commons.IVATRateControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Commons.Shared.VATRateControlStates(entity);
    }

    public new global::Sungero.Commons.IVATRatePageStates Pages
    {
      get { return (global::Sungero.Commons.IVATRatePageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Commons.Shared.VATRatePageStates(entity);
    }

  }


  public class VATRateControlStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryControlStates, global::Sungero.Commons.IVATRateControlStates
  {

    protected internal VATRateControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class VATRatePageStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPageStates, global::Sungero.Commons.IVATRatePageStates
  {
        public global::Sungero.Domain.Shared.IStandalonePageState MainPage
        {
        get { return this.GetPageState<Sungero.Domain.Shared.IStandalonePageState>("Card"); }
        }


    protected internal VATRatePageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class VATRatePropertyStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertyStates, global::Sungero.Commons.IVATRatePropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> Name 
            {
              get { return this.GetPropertyState<global::System.String>("Name"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> Rate 
            {
              get { return this.GetPropertyState<global::System.Int32?>("Rate"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> Sid 
            {
              get { return this.GetPropertyState<global::System.String>("Sid"); }
            }


    protected internal VATRatePropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// VATRateInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Shared
{
  public class VATRateInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryInfo, global::Sungero.Commons.IVATRateInfo
  {
    public VATRateInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Commons.IVATRatePropertiesInfo Properties
    {
      get { return (global::Sungero.Commons.IVATRatePropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Commons.Shared.VATRatePropertiesInfo(entityType);
    }

  }

  public class VATRatePropertiesInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertiesInfo, global::Sungero.Commons.IVATRatePropertiesInfo
  {
        public global::Sungero.Domain.Shared.IStringPropertyInfo Name 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("Name");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo Rate 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("Rate");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IStringPropertyInfo Sid 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("Sid");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }


    protected internal VATRatePropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

// ==================================================================
// VATRateHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons
{
  public partial class VATRateSharedHandlers : global::Sungero.CoreEntities.DatabookEntrySharedHandlers, IVATRateSharedHandlers
  {
    private global::Sungero.Commons.IVATRate _obj
    {
      get { return (global::Sungero.Commons.IVATRate)this.Entity; }
    }
    public virtual void NameChanged(global::Sungero.Domain.Shared.StringPropertyChangedEventArgs e) { }


    public virtual void RateChanged(global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs e) { }


    public virtual void SidChanged(global::Sungero.Domain.Shared.StringPropertyChangedEventArgs e) { }




    public VATRateSharedHandlers(global::Sungero.Commons.IVATRate entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// VATRateResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Shared.VATRate
{
  /// <summary>
  /// Represents VATRate resources.
  /// </summary>
  public class VATRateResources : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryResources, global::Sungero.Commons.VATRate.IVATRateResources
  {
    public virtual global::CommonLibrary.LocalizedString DefaultVatRateWithoutVatName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate) , "DefaultVatRateWithoutVatName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DefaultVatRateWithoutVatNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate), "DefaultVatRateWithoutVatName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DefaultVatRateZeroPercentName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate) , "DefaultVatRateZeroPercentName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DefaultVatRateZeroPercentNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate), "DefaultVatRateZeroPercentName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DefaultVatRateTenPercentName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate) , "DefaultVatRateTenPercentName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DefaultVatRateTenPercentNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate), "DefaultVatRateTenPercentName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DefaultVatRateTwentyPercentName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate) , "DefaultVatRateTwentyPercentName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DefaultVatRateTwentyPercentNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate), "DefaultVatRateTwentyPercentName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RateMustBePositive
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate) , "RateMustBePositive");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RateMustBePositiveFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Commons.IVATRate), "RateMustBePositive", false, args);
    }

  }
}

// ==================================================================
// VATRateSharedFunctions.g.cs
// ==================================================================

namespace Sungero.Commons.Shared
{
  public partial class VATRateFunctions : global::Sungero.CoreEntities.Shared.DatabookEntryFunctions
  {
    private global::Sungero.Commons.IVATRate _obj
    {
      get { return (global::Sungero.Commons.IVATRate)this.Entity; }
    }

    public VATRateFunctions(global::Sungero.Commons.IVATRate entity) : base(entity) { }
  }
}

// ==================================================================
// VATRateFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Functions
{
  internal static class VATRate
  {
  }
}

// ==================================================================
// VATRateFilterState.g.cs
// ==================================================================

namespace Sungero.Commons.Shared.VATRate
{

  public class VATRateFilterInfo : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryFilterInfo,
    global::Sungero.Commons.IVATRateFilterInfo
  {
  }

  public class VATRateFilterState : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryFilterState,
    global::Sungero.Commons.IVATRateFilterState
  {



    public new Sungero.Commons.IVATRateFilterInfo Info
    {
      get
      {
        return (Sungero.Commons.IVATRateFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new Sungero.Commons.Shared.VATRate.VATRateFilterInfo();
    }

  }
}

// ==================================================================
// VATRateSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Shared
{
  public class VATRateSharedPublicFunctions : global::Sungero.Commons.Shared.IVATRateSharedPublicFunctions
  {
  }
}
