
// ==================================================================
// AcquaintanceTaskAddedAddendaState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskAddedAddendaState : 
    global::Sungero.Domain.Shared.ChildEntityState, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaState
  {
    public AcquaintanceTaskAddedAddendaState(global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddenda entity) : base(entity) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskAddedAddendaPropertyStates(entity);
    }


  }


  public class AcquaintanceTaskAddedAddendaPropertyStates : 
    global::Sungero.Domain.Shared.ChildEntityPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
            {
              get { return this.InternalAcquaintanceTask; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> InternalAcquaintanceTask
            {
              get { return this.GetPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask>("AcquaintanceTask"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> AddendumId 
            {
              get { return this.GetPropertyState<global::System.Int32?>("AddendumId"); }
            }


    protected internal AcquaintanceTaskAddedAddendaPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class AcquaintanceTaskAddedAddendaCollectionPropertyState<T> :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyState<T>, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaCollectionPropertyState<T>
    where T : global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddenda
  {
    public new global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaCollectionPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskAddedAddendaCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal AcquaintanceTaskAddedAddendaCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class AcquaintanceTaskAddedAddendaCollectionPropertyStates :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaCollectionPropertyStates
  {
        public global::Sungero.Domain.Shared.IChildPropertySummaryState AcquaintanceTask
        {
          get { return this.GetChildPropertySummaryState("AcquaintanceTask"); }
        }
        public global::Sungero.Domain.Shared.IChildPropertySummaryState AddendumId
        {
          get { return this.GetChildPropertySummaryState("AddendumId"); }
        }


    protected internal AcquaintanceTaskAddedAddendaCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// AcquaintanceTaskAddedAddendaInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskAddedAddendaInfo : 
    global::Sungero.Domain.Shared.ChildEntityInfo, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaInfo
  {
    public AcquaintanceTaskAddedAddendaInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertiesInfo Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskAddedAddendaPropertiesInfo(entityType);
    }

  }

  public class AcquaintanceTaskAddedAddendaPropertiesInfo : 
    global::Sungero.Domain.Shared.ChildEntityPropertiesInfo, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaPropertiesInfo
  {
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("AcquaintanceTask");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo AddendumId 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("AddendumId");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }


    protected internal AcquaintanceTaskAddedAddendaPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
