
// ==================================================================
// PersonEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Parties.Client
{ 
}

// ==================================================================
// PersonHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Parties
{

  public partial class PersonFilteringClientHandler
    : global::Sungero.Parties.CounterpartyFilteringClientHandler
  {
    private global::Sungero.Parties.IPersonFilterState _filter
    {
      get
      {
        return (Sungero.Parties.IPersonFilterState)this.Filter;
      }
    }

    public PersonFilteringClientHandler(global::Sungero.Parties.IPersonFilterState filter)
    : base(filter)
    {
    }

    protected PersonFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
      base.ValidateFilterPanel(e);
    }
  }


  public partial class PersonClientHandlers : global::Sungero.Parties.CounterpartyClientHandlers
  {
    private global::Sungero.Parties.IPerson _obj
    {
      get { return (global::Sungero.Parties.IPerson)this.Entity; }
    }

    public virtual void LastNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void FirstNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void MiddleNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void DateOfBirthValueInput(global::Sungero.Presentation.DateTimeValueInputEventArgs e) { }


    public virtual void SexValueInput(global::Sungero.Presentation.EnumerationValueInputEventArgs e) { }


    public virtual void INILAValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void ShortNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }



    public virtual global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> SexFiltering(
      global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> query) 
    { 
      return query; 
    }





    public PersonClientHandlers(global::Sungero.Parties.IPerson entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// PersonClientFunctions.g.cs
// ==================================================================

namespace Sungero.Parties.Client
{
  public partial class PersonFunctions : global::Sungero.Parties.Client.CounterpartyFunctions
  {
    private global::Sungero.Parties.IPerson _obj
    {
      get { return (global::Sungero.Parties.IPerson)this.Entity; }
    }

    public PersonFunctions(global::Sungero.Parties.IPerson entity) : base(entity) { }
  }
}

// ==================================================================
// PersonFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Parties.Functions
{
  internal static class Person
  {
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Parties.ICounterparty> GetDuplicates(global::Sungero.Parties.IPerson person, global::System.Boolean excludeClosed)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicates", new System.Type[] { typeof(global::System.Boolean) });
      return (global::System.Collections.Generic.List<global::Sungero.Parties.ICounterparty>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { excludeClosed });
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.Nullable<global::Sungero.Core.Enumeration> GetGender(global::Sungero.Parties.IPerson person)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetGender", new System.Type[] {  });
      return (global::System.Nullable<global::Sungero.Core.Enumeration>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  void FillName(global::Sungero.Parties.IPerson person)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillName", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.String GetFullName(global::Sungero.Parties.IPerson person, Sungero.Core.DeclensionCase declensionCase)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFullName", new System.Type[] { typeof(Sungero.Core.DeclensionCase) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { declensionCase });
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.String GetSurnameAndInitialsInTenantCulture(global::System.String firstName, global::System.String middleName, global::System.String lastName)
    {
      var __funcType = Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Parties.Shared.PersonFunctions");
      if (__funcType != null)
      {    
        var __funcMethod = __funcType.GetMethod("GetSurnameAndInitialsInTenantCulture",
          System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic,
          null, new System.Type[] { typeof(global::System.String), typeof(global::System.String), typeof(global::System.String) }, null);
        return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, null, new object[] { firstName, middleName, lastName });
      }
      else
      {
        return global::Sungero.Parties.Shared.PersonFunctions.GetSurnameAndInitialsInTenantCulture(firstName, middleName, lastName);
      }
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.String SetUppercaseFirstLetter(global::System.String source)
    {
      var __funcType = Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Parties.Shared.PersonFunctions");
      if (__funcType != null)
      {    
        var __funcMethod = __funcType.GetMethod("SetUppercaseFirstLetter",
          System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic,
          null, new System.Type[] { typeof(global::System.String) }, null);
        return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, null, new object[] { source });
      }
      else
      {
        return global::Sungero.Parties.Shared.PersonFunctions.SetUppercaseFirstLetter(source);
      }
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.String CheckTin(global::Sungero.Parties.IPerson person, global::System.String tin)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("CheckTin", new System.Type[] { typeof(global::System.String) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { tin });
    }
    /// <redirect project="Sungero.Parties.Shared" type="Sungero.Parties.Shared.PersonFunctions" />
    internal static  global::System.String GetLastNameAndInitials(global::Sungero.Parties.IPerson person, Sungero.Core.DeclensionCase declension)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)person).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetLastNameAndInitials", new System.Type[] { typeof(Sungero.Core.DeclensionCase) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { declension });
    }

  }
}

// ==================================================================
// PersonClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Parties.Client
{
  public class PersonClientPublicFunctions : global::Sungero.Parties.Client.IPersonClientPublicFunctions
  {
  }
}

// ==================================================================
// PersonActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Parties.Client
{
  public partial class PersonActions : global::Sungero.Parties.Client.CounterpartyActions
  {
    private global::Sungero.Parties.IPerson _obj { get { return (global::Sungero.Parties.IPerson)this.Entity; } }
    public PersonActions(global::Sungero.Parties.IPerson entity) : base(entity) { }
  }

  public partial class PersonCollectionActions : global::Sungero.Parties.Client.CounterpartyCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Parties.IPerson> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Parties.IPerson>(this.Entities); }
    }
  }

  public partial class PersonCollectionBulkActions : global::Sungero.Parties.Client.CounterpartyCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int32> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class PersonAnyChildEntityActions : global::Sungero.Parties.Client.CounterpartyAnyChildEntityActions
  {
  }

  public partial class PersonAnyChildEntityCollectionActions : global::Sungero.Parties.Client.CounterpartyAnyChildEntityCollectionActions
  {
  }



}
