
// ==================================================================
// AcquaintanceTaskRemovedAddendaState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskRemovedAddendaState : 
    global::Sungero.Domain.Shared.ChildEntityState, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaState
  {
    public AcquaintanceTaskRemovedAddendaState(global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddenda entity) : base(entity) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskRemovedAddendaPropertyStates(entity);
    }


  }


  public class AcquaintanceTaskRemovedAddendaPropertyStates : 
    global::Sungero.Domain.Shared.ChildEntityPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
            {
              get { return this.InternalAcquaintanceTask; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> InternalAcquaintanceTask
            {
              get { return this.GetPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask>("AcquaintanceTask"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> AddendumId 
            {
              get { return this.GetPropertyState<global::System.Int32?>("AddendumId"); }
            }


    protected internal AcquaintanceTaskRemovedAddendaPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class AcquaintanceTaskRemovedAddendaCollectionPropertyState<T> :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyState<T>, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaCollectionPropertyState<T>
    where T : global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddenda
  {
    public new global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaCollectionPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskRemovedAddendaCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal AcquaintanceTaskRemovedAddendaCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class AcquaintanceTaskRemovedAddendaCollectionPropertyStates :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaCollectionPropertyStates
  {
        public global::Sungero.Domain.Shared.IChildPropertySummaryState AcquaintanceTask
        {
          get { return this.GetChildPropertySummaryState("AcquaintanceTask"); }
        }
        public global::Sungero.Domain.Shared.IChildPropertySummaryState AddendumId
        {
          get { return this.GetChildPropertySummaryState("AddendumId"); }
        }


    protected internal AcquaintanceTaskRemovedAddendaCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// AcquaintanceTaskRemovedAddendaInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskRemovedAddendaInfo : 
    global::Sungero.Domain.Shared.ChildEntityInfo, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaInfo
  {
    public AcquaintanceTaskRemovedAddendaInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertiesInfo Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskRemovedAddendaPropertiesInfo(entityType);
    }

  }

  public class AcquaintanceTaskRemovedAddendaPropertiesInfo : 
    global::Sungero.Domain.Shared.ChildEntityPropertiesInfo, global::Sungero.RecordManagement.IAcquaintanceTaskRemovedAddendaPropertiesInfo
  {
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("AcquaintanceTask");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo AddendumId 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("AddendumId");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }


    protected internal AcquaintanceTaskRemovedAddendaPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
