
// ==================================================================
// FormalizedPowerOfAttorney.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
    public class FormalizedPowerOfAttorneyFilter<T> :
      global::Sungero.Docflow.Server.PowerOfAttorneyBaseFilter<T>
      where T : class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
    {
      private global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState filter
      {
        get
        {
          return (Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.Filter;
        }
      }

      protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
      {
        return base.ApplyAppliedFilter(query);
      }

      public FormalizedPowerOfAttorneyFilter(global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState filter)
      : base(filter)
      {
      }

      protected FormalizedPowerOfAttorneyFilter()
      {
      }
    }
    public class FormalizedPowerOfAttorneySearchDialogModel : global::Sungero.Docflow.Server.PowerOfAttorneyBaseSearchDialogModel
        {
                  public override global::System.Int32? Id { get; protected set; }
                  public override global::System.String Name { get; protected set; }
                  public override global::System.String Subject { get; protected set; }


                  public override global::System.Collections.Generic.IEnumerable<Sungero.Content.IAssociatedApplication> AssociatedApplication { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Core.Enumeration> VerificationState { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.CoreEntities.IRecipient> PreparedBy { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.CoreEntities.IRecipient> Author { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<CommonLibrary.DateRangeValue> Created { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Docflow.IDocumentKind> DocumentKind { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Company.IBusinessUnit> BusinessUnit { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Company.IDepartment> Department { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.CoreEntities.IRecipient> OurSignatory { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.CoreEntities.IRecipient> IssuedTo { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<CommonLibrary.DateRangeValue> ValidFrom { get; protected set; }


                  public virtual global::System.String UnifiedRegistrationNumber { get; protected set; }



                   public new FormalizedPowerOfAttorneyVersionsModel Versions { get { return (FormalizedPowerOfAttorneyVersionsModel)base.Versions; } protected set { base.Versions = value; } }
                   [Sungero.Domain.Shared.HideInDevStudio()]
                   public new FormalizedPowerOfAttorneyTrackingModel Tracking { get { return (FormalizedPowerOfAttorneyTrackingModel)base.Tracking; } protected set { base.Tracking = value; } }

        }

      public class FormalizedPowerOfAttorneyVersionsModel : global::Sungero.Docflow.Server.PowerOfAttorneyBaseVersionsModel
          {
                      [Sungero.Domain.Shared.HideInDevStudio()]
                      public override global::System.Int32? Id { get; protected set; }
                      public override global::System.String Body { get; protected set; }




         }
      public class FormalizedPowerOfAttorneyTrackingModel : global::Sungero.Docflow.Server.PowerOfAttorneyBaseTrackingModel
          {
                      [Sungero.Domain.Shared.HideInDevStudio()]
                      public override global::System.Int32? Id { get; protected set; }




         }





  [global::Sungero.Domain.Filter(typeof(global::Sungero.Docflow.Server.FormalizedPowerOfAttorneyFilter<global::Sungero.Docflow.IFormalizedPowerOfAttorney>))]

  public class FormalizedPowerOfAttorney :
    global::Sungero.Docflow.Server.PowerOfAttorneyBase, global::Sungero.Docflow.IFormalizedPowerOfAttorney, global::Sungero.Domain.Shared.ISecurableEntity, global::Sungero.Domain.IInternalSecurableEntity
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("104472db-b71b-42a8-bca5-581a08d1ca7b");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Docflow.Server.FormalizedPowerOfAttorney.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Docflow.IFormalizedPowerOfAttorney, Sungero.Domain.Interfaces"; }
    }

    public override string DisplayValue
    {
      get { return this.Name; }
      set { this.Name = value; }
    }

    public new virtual global::Sungero.Docflow.IFormalizedPowerOfAttorneyState State
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyState(this);
    }

    public new virtual global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo Info
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo)base.Info; }
    }

    public new virtual global::Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights AccessRights
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights)base.AccessRights; }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Docflow.Server.FormalizedPowerOfAttorneyAccessRights(this);
    }

    protected override global::Sungero.Domain.EntityFunctions CreateServerFunctions()
    {
      return new global::Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions(this);
    }

    protected override object CreateHandlers() {
      return new global::Sungero.Docflow.FormalizedPowerOfAttorneyServerHandlers(this);
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.Docflow.FormalizedPowerOfAttorneySharedHandlers(this);
    }

    private global::System.String _UnifiedRegistrationNumber;
    public virtual global::System.String UnifiedRegistrationNumber
    {
      get
      {
        return this._UnifiedRegistrationNumber;
      }

      set
      {
        this.SetPropertyValue("UnifiedRegistrationNumber", this._UnifiedRegistrationNumber, value, (propertyValue) => { this._UnifiedRegistrationNumber = propertyValue; }, this.UnifiedRegistrationNumberChangedHandler);
      }
    }









    protected override global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Content.IElectronicDocumentVersions> CreateVersionsCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>() { RootEntity = this };
    }
    protected override global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.IOfficialDocumentTracking> CreateTrackingCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTracking>() { RootEntity = this };
    }


    protected override global::Sungero.Domain.Shared.EntityCreatingFromServerHandler CreateCreatingFromServerHandler(
      global::Sungero.Domain.Shared.IEntity entitySource)
    {
      var instance = Sungero.Metadata.Services.AppliedTypesManager.CreateInstance("Sungero.Docflow.FormalizedPowerOfAttorneyCreatingFromServerHandler", new object[] { (global::Sungero.Docflow.IFormalizedPowerOfAttorney)entitySource, this.Info });
      if (instance != null)
        return (global::Sungero.Domain.Shared.EntityCreatingFromServerHandler)instance;

      return new global::Sungero.Docflow.FormalizedPowerOfAttorneyCreatingFromServerHandler((global::Sungero.Docflow.IFormalizedPowerOfAttorney)entitySource, this.Info);
    }

    #region Framework events

    protected void UnifiedRegistrationNumberChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.UnifiedRegistrationNumber, this.UnifiedRegistrationNumber, this);
     ((global::Sungero.Docflow.IFormalizedPowerOfAttorneySharedHandlers)this.SharedHandlers).UnifiedRegistrationNumberChanged(args);
    }





    #endregion


    public FormalizedPowerOfAttorney()
    {
    }

    protected override global::Sungero.Domain.Shared.EntityConvertingFromServerHandler CreateConvertingFromServerHandler(   
      global::Sungero.Domain.Shared.IEntity entitySource)
    {
      var instance = Sungero.Metadata.Services.AppliedTypesManager.CreateInstance("Sungero.Docflow.FormalizedPowerOfAttorneyConvertingFromServerHandler", (global::Sungero.Content.IElectronicDocument)entitySource, this.Info);
      if (instance != null)
        return (global::Sungero.Domain.Shared.EntityConvertingFromServerHandler)instance;

      return new global::Sungero.Docflow.FormalizedPowerOfAttorneyConvertingFromServerHandler((global::Sungero.Content.IElectronicDocument)entitySource, this.Info);
    }

  }
}

// ==================================================================
// FormalizedPowerOfAttorneyHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{

  public partial class FormalizedPowerOfAttorneyFilteringServerHandler<T>
    : global::Sungero.Docflow.PowerOfAttorneyBaseFilteringServerHandler<T>  
    where T : class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState _filter
    {
      get
      {
        return (Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.Filter;
      }
    }

    public FormalizedPowerOfAttorneyFilteringServerHandler(global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState filter)
    : base(filter)
    {
    }

    protected FormalizedPowerOfAttorneyFilteringServerHandler()
    {
    }

    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.FilteringEventArgs e)
    {
      query = base.Filtering(query, e);
            return query;
    }

      public override global::System.Linq.IQueryable<Sungero.Docflow.IDocumentRegister> DocumentRegisterFiltering(global::System.Linq.IQueryable<Sungero.Docflow.IDocumentRegister> query, global::Sungero.Domain.FilteringEventArgs e)
      {
        query = base.DocumentRegisterFiltering(query, e);
              return query;
      }

      public override global::System.Linq.IQueryable<Sungero.Docflow.IDocumentKind> DocumentKindFiltering(global::System.Linq.IQueryable<Sungero.Docflow.IDocumentKind> query, global::Sungero.Domain.FilteringEventArgs e)
      {
        query = base.DocumentKindFiltering(query, e);
              return query;
      }

      public override global::System.Linq.IQueryable<Sungero.Company.IBusinessUnit> BusinessUnitFiltering(global::System.Linq.IQueryable<Sungero.Company.IBusinessUnit> query, global::Sungero.Domain.FilteringEventArgs e)
      {
        query = base.BusinessUnitFiltering(query, e);
              return query;
      }

      public override global::System.Linq.IQueryable<Sungero.Company.IDepartment> DepartmentFiltering(global::System.Linq.IQueryable<Sungero.Company.IDepartment> query, global::Sungero.Domain.FilteringEventArgs e)
      {
        query = base.DepartmentFiltering(query, e);
              return query;
      }

      public override global::System.Linq.IQueryable<Sungero.Company.IEmployee> PerformerFiltering(global::System.Linq.IQueryable<Sungero.Company.IEmployee> query, global::Sungero.Domain.FilteringEventArgs e)
      {
        query = base.PerformerFiltering(query, e);
              return query;
      }


  }

  public partial class FormalizedPowerOfAttorneySearchDialogServerHandler : global::Sungero.Docflow.PowerOfAttorneyBaseSearchDialogServerHandler
   {
     private global::Sungero.Docflow.Server.FormalizedPowerOfAttorneySearchDialogModel _dialog
     {
       get
       {
         return (global::Sungero.Docflow.Server.FormalizedPowerOfAttorneySearchDialogModel)this.Dialog;
       }
     }

     public FormalizedPowerOfAttorneySearchDialogServerHandler(global::Sungero.Docflow.Server.FormalizedPowerOfAttorneySearchDialogModel dialog)
       : base(dialog)
     {
     }
   }

  public partial class FormalizedPowerOfAttorneyServerHandlers : global::Sungero.Docflow.PowerOfAttorneyBaseServerHandlers
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }

    public FormalizedPowerOfAttorneyServerHandlers(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity)
      : base(entity)
    {
    }
  }

  public partial class FormalizedPowerOfAttorneyCreatingFromServerHandler : global::Sungero.Docflow.PowerOfAttorneyBaseCreatingFromServerHandler
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _source
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Source; }
    }

    private global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo _info
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo)this._Info; }
    }

    public FormalizedPowerOfAttorneyCreatingFromServerHandler(global::Sungero.Docflow.IFormalizedPowerOfAttorney source, global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo info)
      : base(source, info)
    {
    }
  }

}

// ==================================================================
// FormalizedPowerOfAttorneyEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
}

// ==================================================================
// FormalizedPowerOfAttorneyAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
  public class FormalizedPowerOfAttorneyAccessRights : 
    Sungero.Docflow.Server.PowerOfAttorneyBaseAccessRights, Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights
  {

    public FormalizedPowerOfAttorneyAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class FormalizedPowerOfAttorneyTypeAccessRights : 
    Sungero.Docflow.Server.PowerOfAttorneyBaseTypeAccessRights, Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights
  {

    public FormalizedPowerOfAttorneyTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
    public class FormalizedPowerOfAttorneyRepositoryImplementer<T> : 
      global::Sungero.Docflow.Server.PowerOfAttorneyBaseRepositoryImplementer<T>,
      global::Sungero.Docflow.IFormalizedPowerOfAttorneyRepositoryImplementer<T>
      where T : global::Sungero.Docflow.IFormalizedPowerOfAttorney 
    {
       public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights AccessRights
       {
          get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo Info
       {
          get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Docflow.Server.FormalizedPowerOfAttorneyTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// FormalizedPowerOfAttorneyPanelNavigationFilters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
    public class FormalizedPowerOfAttorneyDocumentRegisterPanelNavigationFilter : global::Sungero.Docflow.Server.PowerOfAttorneyBaseDocumentRegisterPanelNavigationFilter
    {
      private global::System.Linq.IQueryable Apply<T>(global::System.Linq.IQueryable query) where T: class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
      {
        var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentRegister>)query;
        var typedState = (global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.State;
        var handlers = new global::Sungero.Docflow.FormalizedPowerOfAttorneyFilteringServerHandler<T>(typedState);
        var args = new global::Sungero.Domain.FilteringEventArgs();
        var result = handlers.DocumentRegisterFiltering(typedQuery, args);
        if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<global::Sungero.Docflow.IDocumentRegister>();
        return result;
      }

      public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
      {
        return this.Apply<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(query);
      }
    }

    public class FormalizedPowerOfAttorneyDocumentKindPanelNavigationFilter : global::Sungero.Docflow.Server.PowerOfAttorneyBaseDocumentKindPanelNavigationFilter
    {
      private global::System.Linq.IQueryable Apply<T>(global::System.Linq.IQueryable query) where T: class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
      {
        var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentKind>)query;
        var typedState = (global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.State;
        var handlers = new global::Sungero.Docflow.FormalizedPowerOfAttorneyFilteringServerHandler<T>(typedState);
        var args = new global::Sungero.Domain.FilteringEventArgs();
        var result = handlers.DocumentKindFiltering(typedQuery, args);
        if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<global::Sungero.Docflow.IDocumentKind>();
        return result;
      }

      public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
      {
        return this.Apply<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(query);
      }
    }

    public class FormalizedPowerOfAttorneyBusinessUnitPanelNavigationFilter : global::Sungero.Docflow.Server.PowerOfAttorneyBaseBusinessUnitPanelNavigationFilter
    {
      private global::System.Linq.IQueryable Apply<T>(global::System.Linq.IQueryable query) where T: class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
      {
        var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Company.IBusinessUnit>)query;
        var typedState = (global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.State;
        var handlers = new global::Sungero.Docflow.FormalizedPowerOfAttorneyFilteringServerHandler<T>(typedState);
        var args = new global::Sungero.Domain.FilteringEventArgs();
        var result = handlers.BusinessUnitFiltering(typedQuery, args);
        if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<global::Sungero.Company.IBusinessUnit>();
        return result;
      }

      public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
      {
        return this.Apply<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(query);
      }
    }

    public class FormalizedPowerOfAttorneyDepartmentPanelNavigationFilter : global::Sungero.Docflow.Server.PowerOfAttorneyBaseDepartmentPanelNavigationFilter
    {
      private global::System.Linq.IQueryable Apply<T>(global::System.Linq.IQueryable query) where T: class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
      {
        var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Company.IDepartment>)query;
        var typedState = (global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.State;
        var handlers = new global::Sungero.Docflow.FormalizedPowerOfAttorneyFilteringServerHandler<T>(typedState);
        var args = new global::Sungero.Domain.FilteringEventArgs();
        var result = handlers.DepartmentFiltering(typedQuery, args);
        if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<global::Sungero.Company.IDepartment>();
        return result;
      }

      public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
      {
        return this.Apply<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(query);
      }
    }

    public class FormalizedPowerOfAttorneyPerformerPanelNavigationFilter : global::Sungero.Docflow.Server.PowerOfAttorneyBasePerformerPanelNavigationFilter
    {
      private global::System.Linq.IQueryable Apply<T>(global::System.Linq.IQueryable query) where T: class, global::Sungero.Docflow.IFormalizedPowerOfAttorney
      {
        var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Company.IEmployee>)query;
        var typedState = (global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.State;
        var handlers = new global::Sungero.Docflow.FormalizedPowerOfAttorneyFilteringServerHandler<T>(typedState);
        var args = new global::Sungero.Domain.FilteringEventArgs();
        var result = handlers.PerformerFiltering(typedQuery, args);
        if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<global::Sungero.Company.IEmployee>();
        return result;
      }

      public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
      {
        return this.Apply<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(query);
      }
    }

}

// ==================================================================
// FormalizedPowerOfAttorneyServerFunctions.g.cs
// ==================================================================

namespace Sungero.Docflow.Server
{
  public partial class FormalizedPowerOfAttorneyFunctions : global::Sungero.Docflow.Server.PowerOfAttorneyBaseFunctions
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }

    public FormalizedPowerOfAttorneyFunctions(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity) { }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Functions
{
  internal static class FormalizedPowerOfAttorney
  {
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static  void ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ImportFormalizedPowerOfAttorneyFromXmlAndSign", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray), typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml, signature });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::Sungero.Docflow.Structures.Module.IByteArray ConvertSignatureFromBase64(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ConvertSignatureFromBase64", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
      return (global::Sungero.Docflow.Structures.Module.IByteArray)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { signature });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ValidateFormalizedPowerOfAttorneyXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ValidateFormalizedPowerOfAttorneyXml", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void VerifyExternalSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("VerifyExternalSignature", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray), typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml, signature });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillFormalizedPowerOfAttorney(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillFormalizedPowerOfAttorney", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  System.Xml.Linq.XElement TryGetPoaInfoElement(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("TryGetPoaInfoElement", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
      return (System.Xml.Linq.XElement)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  System.Xml.Linq.XElement TryGetPoaInfoElement(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, global::System.String poaElementName, global::System.String documentElementName, global::System.String poaInfoElementName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("TryGetPoaInfoElement", new System.Type[] { typeof(System.Xml.Linq.XDocument), typeof(global::System.String), typeof(global::System.String), typeof(global::System.String) });
      return (System.Xml.Linq.XElement)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc, poaElementName, documentElementName, poaInfoElementName });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillUnifiedRegistrationNumberFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, System.Xml.Linq.XElement powerOfAttorneyInfo, global::System.String poaUnifiedRegNumberAttributeName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillUnifiedRegistrationNumberFromXml", new System.Type[] { typeof(System.Xml.Linq.XDocument), typeof(System.Xml.Linq.XElement), typeof(global::System.String) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc, powerOfAttorneyInfo, poaUnifiedRegNumberAttributeName });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillValidDatesFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, System.Xml.Linq.XElement powerOfAttorneyInfo, global::System.String poaValidFromAttributeName, global::System.String poaValidTillAttributeName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillValidDatesFromXml", new System.Type[] { typeof(System.Xml.Linq.XDocument), typeof(System.Xml.Linq.XElement), typeof(global::System.String), typeof(global::System.String) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc, powerOfAttorneyInfo, poaValidFromAttributeName, poaValidTillAttributeName });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillRegistrationData(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.String number, global::System.Nullable<global::System.DateTime> date)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillRegistrationData", new System.Type[] { typeof(global::System.String), typeof(global::System.Nullable<global::System.DateTime>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { number, date });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillIssuedToFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillIssuedToFromXml", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillDocumentName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillDocumentName", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void WriteFormalizedPowerOfAttorneyBody(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("WriteFormalizedPowerOfAttorneyBody", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ImportSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ImportSignature", new System.Type[] { typeof(global::Sungero.Docflow.Structures.Module.IByteArray), typeof(global::Sungero.Docflow.Structures.Module.IByteArray) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xml, signature });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  void CheckSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("CheckSignature", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Nullable<global::System.DateTime> GetDateFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement element, global::System.String attributeName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDateFromXml", new System.Type[] { typeof(System.Xml.Linq.XElement), typeof(global::System.String) });
      return (global::System.Nullable<global::System.DateTime>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { element, attributeName });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::Sungero.Docflow.Structures.FormalizedPowerOfAttorney.IIssuedToInfo GetIssuedToInfoFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetIssuedToInfoFromXml", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
      return (global::Sungero.Docflow.Structures.FormalizedPowerOfAttorney.IIssuedToInfo)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Collections.Generic.List<System.Xml.Linq.XElement> GetRepresentativeElements(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetRepresentativeElements", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
      return (global::System.Collections.Generic.List<System.Xml.Linq.XElement>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetPoaFormatVersionFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetPoaFormatVersionFromXml", new System.Type[] { typeof(System.Xml.Linq.XDocument) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { xdoc });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetIssuedToFullNameFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement individualElement)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetIssuedToFullNameFromXml", new System.Type[] { typeof(System.Xml.Linq.XElement) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { individualElement });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetAttributeValueByName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement element, global::System.String attributeName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetAttributeValueByName", new System.Type[] { typeof(System.Xml.Linq.XElement), typeof(global::System.String) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { element, attributeName });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFormalizedPowerOfAttorneyDuplicates", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Boolean IsNumberValidationDisabled(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("IsNumberValidationDisabled", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeRegistrationPaneVisibility(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean needShow, global::System.Boolean repeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeRegistrationPaneVisibility", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { needShow, repeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetActiveLifeCycleState(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetActiveLifeCycleState", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Boolean CheckRegistrationNumberUnique(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("CheckRegistrationNumberUnique", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillName", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeDocumentPropertiesAccess(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean isEnabled, global::System.Boolean isRepeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeDocumentPropertiesAccess", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { isEnabled, isRepeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetRequiredProperties(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetDuplicatesErrorText(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicatesErrorText", new System.Type[] {  });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicates", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

  }
}

// ==================================================================
// FormalizedPowerOfAttorneyServerPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
  public class FormalizedPowerOfAttorneyServerPublicFunctions : global::Sungero.Docflow.Server.IFormalizedPowerOfAttorneyServerPublicFunctions
  {
    public void CheckSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.CheckSignature(formalizedPowerOfAttorney);
    }
    public global::Sungero.Docflow.Structures.Module.IByteArray ConvertSignatureFromBase64(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.ConvertSignatureFromBase64(formalizedPowerOfAttorney, signature);
    }
    public void FillDocumentName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillDocumentName(formalizedPowerOfAttorney, xdoc);
    }
    public void FillFormalizedPowerOfAttorney(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillFormalizedPowerOfAttorney(formalizedPowerOfAttorney, xml);
    }
    public void FillIssuedToFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillIssuedToFromXml(formalizedPowerOfAttorney, xdoc);
    }
    public void FillRegistrationData(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.String number, global::System.Nullable<global::System.DateTime> date)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillRegistrationData(formalizedPowerOfAttorney, number, date);
    }
    public void FillUnifiedRegistrationNumberFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, System.Xml.Linq.XElement powerOfAttorneyInfo, global::System.String poaUnifiedRegNumberAttributeName)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillUnifiedRegistrationNumberFromXml(formalizedPowerOfAttorney, xdoc, powerOfAttorneyInfo, poaUnifiedRegNumberAttributeName);
    }
    public void FillValidDatesFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, System.Xml.Linq.XElement powerOfAttorneyInfo, global::System.String poaValidFromAttributeName, global::System.String poaValidTillAttributeName)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.FillValidDatesFromXml(formalizedPowerOfAttorney, xdoc, powerOfAttorneyInfo, poaValidFromAttributeName, poaValidTillAttributeName);
    }
    public global::System.String GetAttributeValueByName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement element, global::System.String attributeName)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetAttributeValueByName(formalizedPowerOfAttorney, element, attributeName);
    }
    public global::System.Nullable<global::System.DateTime> GetDateFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement element, global::System.String attributeName)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetDateFromXml(formalizedPowerOfAttorney, element, attributeName);
    }
    public global::System.String GetIssuedToFullNameFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XElement individualElement)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetIssuedToFullNameFromXml(formalizedPowerOfAttorney, individualElement);
    }
    public global::Sungero.Docflow.Structures.FormalizedPowerOfAttorney.IIssuedToInfo GetIssuedToInfoFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetIssuedToInfoFromXml(formalizedPowerOfAttorney, xdoc);
    }
    public global::System.String GetPoaFormatVersionFromXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetPoaFormatVersionFromXml(formalizedPowerOfAttorney, xdoc);
    }
    public global::System.Collections.Generic.List<System.Xml.Linq.XElement> GetRepresentativeElements(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.GetRepresentativeElements(formalizedPowerOfAttorney, xdoc);
    }
    public void ImportSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.ImportSignature(formalizedPowerOfAttorney, xml, signature);
    }
    public System.Xml.Linq.XElement TryGetPoaInfoElement(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.TryGetPoaInfoElement(formalizedPowerOfAttorney, xdoc);
    }
    public System.Xml.Linq.XElement TryGetPoaInfoElement(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, System.Xml.Linq.XDocument xdoc, global::System.String poaElementName, global::System.String documentElementName, global::System.String poaInfoElementName)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.TryGetPoaInfoElement(formalizedPowerOfAttorney, xdoc, poaElementName, documentElementName, poaInfoElementName);
    }
    public void ValidateFormalizedPowerOfAttorneyXml(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.ValidateFormalizedPowerOfAttorneyXml(formalizedPowerOfAttorney, xml);
    }
    public void VerifyExternalSignature(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.VerifyExternalSignature(formalizedPowerOfAttorney, xml, signature);
    }
    public void WriteFormalizedPowerOfAttorneyBody(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.WriteFormalizedPowerOfAttorneyBody(formalizedPowerOfAttorney, xml);
    }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Queries
{
  public class FormalizedPowerOfAttorney
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.Docflow.Server.FormalizedPowerOfAttorney.FormalizedPowerOfAttorneyQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyServerHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{
  public partial class FormalizedPowerOfAttorneyConvertingFromServerHandler : global::Sungero.Docflow.PowerOfAttorneyBaseConvertingFromServerHandler
  { 
    private global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo _info
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo)this._Info; }
    }

    public FormalizedPowerOfAttorneyConvertingFromServerHandler(global::Sungero.Content.IElectronicDocument source, global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo info)
      : base(source, info)
    {
    }
  }
}
