
// ==================================================================
// FormalizedPowerOfAttorneyEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{ 
}

// ==================================================================
// FormalizedPowerOfAttorneyHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{

  public partial class FormalizedPowerOfAttorneyFilteringClientHandler
    : global::Sungero.Docflow.PowerOfAttorneyBaseFilteringClientHandler
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState _filter
    {
      get
      {
        return (Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState)this.Filter;
      }
    }

    public FormalizedPowerOfAttorneyFilteringClientHandler(global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState filter)
    : base(filter)
    {
    }

    protected FormalizedPowerOfAttorneyFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
      base.ValidateFilterPanel(e);
    }
  }


  public partial class FormalizedPowerOfAttorneyClientHandlers : global::Sungero.Docflow.PowerOfAttorneyBaseClientHandlers
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }

    public FormalizedPowerOfAttorneyClientHandlers(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// FormalizedPowerOfAttorneyClientFunctions.g.cs
// ==================================================================

namespace Sungero.Docflow.Client
{
  public partial class FormalizedPowerOfAttorneyFunctions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseFunctions
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }

    public FormalizedPowerOfAttorneyFunctions(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity) { }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Functions
{
  internal static class FormalizedPowerOfAttorney
  {
    /// <redirect project="Sungero.Docflow.Client" type="Sungero.Docflow.Client.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Boolean ShowImportVersionWithSignatureDialog(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.ClientFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ShowImportVersionWithSignatureDialog", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeRegistrationPaneVisibility(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean needShow, global::System.Boolean repeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeRegistrationPaneVisibility", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { needShow, repeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetActiveLifeCycleState(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetActiveLifeCycleState", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Boolean CheckRegistrationNumberUnique(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("CheckRegistrationNumberUnique", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillName", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeDocumentPropertiesAccess(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean isEnabled, global::System.Boolean isRepeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeDocumentPropertiesAccess", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { isEnabled, isRepeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetRequiredProperties(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetDuplicatesErrorText(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicatesErrorText", new System.Type[] {  });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicates", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    internal static class Remote
    {
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
      internal static  void ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
      {
      global::Sungero.Domain.Shared.RemoteFunctionExecutor.Execute(
          global::System.Guid.Parse("104472db-b71b-42a8-bca5-581a08d1ca7b"),
          "ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney,global::Sungero.Docflow.Structures.Module.IByteArray,global::Sungero.Docflow.Structures.Module.IByteArray)"
          , formalizedPowerOfAttorney, xml, signature);
      }
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
      internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>>(
          global::System.Guid.Parse("104472db-b71b-42a8-bca5-581a08d1ca7b"),
          "GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney)"
          , formalizedPowerOfAttorney);
      }

    }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class FormalizedPowerOfAttorneyClientPublicFunctions : global::Sungero.Docflow.Client.IFormalizedPowerOfAttorneyClientPublicFunctions
  {
    public global::System.Boolean ShowImportVersionWithSignatureDialog(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.ShowImportVersionWithSignatureDialog(formalizedPowerOfAttorney);
    }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public partial class FormalizedPowerOfAttorneyActions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseActions
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj { get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; } }
    public FormalizedPowerOfAttorneyActions(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity) { }
  }

  public partial class FormalizedPowerOfAttorneyCollectionActions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Docflow.IFormalizedPowerOfAttorney> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Docflow.IFormalizedPowerOfAttorney>(this.Entities); }
    }
  }

  public partial class FormalizedPowerOfAttorneyCollectionBulkActions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int32> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class FormalizedPowerOfAttorneyAnyChildEntityActions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseAnyChildEntityActions
  {
  }

  public partial class FormalizedPowerOfAttorneyAnyChildEntityCollectionActions : global::Sungero.Docflow.Client.PowerOfAttorneyBaseAnyChildEntityCollectionActions
  {
  }



  public partial class FormalizedPowerOfAttorneyVersionsActions : global::Sungero.Docflow.Client.OfficialDocumentVersionsActions
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions _obj { get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions)this.Entity; } }
    private global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions> _all
    {
      get { return (global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>)this.AllEntities; }
    }
  }

  public partial class FormalizedPowerOfAttorneyVersionsCollectionActions : global::Sungero.Docflow.Client.OfficialDocumentVersionsCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>(this.Entities); }
    }
    private global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions> _all
    {
      get { return (global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>)this.AllEntities; }
    }
  }



}
