
// ==================================================================
// EntityRecognitionInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
    public class EntityRecognitionInfoFilter<T> :
      global::Sungero.Domain.EntityFilterBase<T>
      where T : class, global::Sungero.Commons.IEntityRecognitionInfo
    {
      protected new global::Sungero.Commons.IEntityRecognitionInfoFilterState Filter { get; private set; }

      private global::Sungero.Commons.IEntityRecognitionInfoFilterState filter
      {
        get
        {
          return this.Filter;
        }
      }

      protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
      {
        return base.ApplyAppliedFilter(query);
      }

      public EntityRecognitionInfoFilter(global::Sungero.Commons.IEntityRecognitionInfoFilterState filter)
      : base()
      {
        this.Filter = filter;
      }

      protected EntityRecognitionInfoFilter()
      {
      }
    }
      public class EntityRecognitionInfoUiFilter<T> :
        global::Sungero.Domain.EntityUiFilterBase<T>
        where T : class, global::Sungero.Commons.IEntityRecognitionInfo
      {
        protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
        {
          return base.ApplyAppliedFilter(query);
        }
      }

    public class EntityRecognitionInfoSearchDialogModel : global::Sungero.CoreEntities.Server.DatabookEntrySearchDialogModel
        {
                  public override global::System.Int32? Id { get; protected set; }



                  public virtual global::System.String Name { get; protected set; }
                  public virtual global::System.String RecognizedClass { get; protected set; }
                  public virtual global::System.Int32? EntityId { get; protected set; }
                  public virtual global::System.String EntityType { get; protected set; }
                  public virtual global::System.String VerifiedClass { get; protected set; }


                  public virtual global::System.Collections.Generic.IEnumerable<Sungero.Core.Enumeration> ClassifierTrainingStatus { get; protected set; }
                  public virtual global::System.Collections.Generic.IEnumerable<Sungero.Commons.IClassifierTrainingSession> ClassifierTrainingSession { get; protected set; }
                  public virtual global::System.Collections.Generic.IEnumerable<CommonLibrary.DateRangeValue> Created { get; protected set; }


                   [Sungero.Domain.Shared.HideInDevStudio()]
                   public EntityRecognitionInfoFactsModel Facts { get; protected set; }
                   [Sungero.Domain.Shared.HideInDevStudio()]
                   public EntityRecognitionInfoAdditionalClassifiersModel AdditionalClassifiers { get; protected set; }

        }


      public class EntityRecognitionInfoFactsModel : global::Sungero.Domain.CollectionPropertySearchDialogModel
          {
            public override global::System.Int32? Id { get; protected set; }


         }
      public class EntityRecognitionInfoAdditionalClassifiersModel : global::Sungero.Domain.CollectionPropertySearchDialogModel
          {
            public override global::System.Int32? Id { get; protected set; }


         }



  public class EntityRecognitionInfoFilterForClassifierTrainingSession<TQueryEntity, TSourceEntity>
    : global::Sungero.Domain.EntityPropertyFilterBase<TQueryEntity, TSourceEntity>
    where TQueryEntity : class, global::Sungero.Commons.IClassifierTrainingSession
    where TSourceEntity : class, global::Sungero.Commons.IEntityRecognitionInfo
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, TSourceEntity sourceEntity)
    {
      var args = new global::Sungero.Domain.PropertyFilteringEventArgs(sourceEntity);
      global::System.Linq.IQueryable<TQueryEntity> result;
      var filterType = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoClassifierTrainingSessionPropertyFilteringServerHandler`1");
      if (filterType != null)
      {
        var genericType = filterType.MakeGenericType(typeof(TQueryEntity));
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(genericType, new object[] { sourceEntity });
        var methodInfo = genericType.GetMethod("ClassifierTrainingSessionFiltering");
        result = (global::System.Linq.IQueryable<TQueryEntity>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { query, args });
      }
      else
      {
        result = new global::Sungero.Commons.EntityRecognitionInfoClassifierTrainingSessionPropertyFilteringServerHandler<TQueryEntity>(sourceEntity).ClassifierTrainingSessionFiltering(query, args);
      }
      if (args.DisableUiFiltering)
        global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public EntityRecognitionInfoFilterForClassifierTrainingSession(string propertyName)
      : base(propertyName)
    {
    }
  }

  public class EntityRecognitionInfoSearchFilterForClassifierTrainingSession<TQueryEntity>
    : global::Sungero.Domain.SearchDialogPropertyFilter<TQueryEntity>
    where TQueryEntity : class, global::Sungero.Commons.IClassifierTrainingSession
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, System.Guid entityType)
    {
      var args = new global::Sungero.Domain.PropertySearchDialogFilteringEventArgs(entityType);
      global::System.Linq.IQueryable<TQueryEntity> result;
      var filterType = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoClassifierTrainingSessionSearchPropertyFilteringServerHandler`1");
      if (filterType != null)
      {
        var genericType = filterType.MakeGenericType(typeof(TQueryEntity));
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(genericType);
        var methodInfo = genericType.GetMethod("ClassifierTrainingSessionSearchDialogFiltering");
        result = (global::System.Linq.IQueryable<TQueryEntity>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { query, args });
      }
      else
      {
        result = new global::Sungero.Commons.EntityRecognitionInfoClassifierTrainingSessionSearchPropertyFilteringServerHandler<TQueryEntity>().ClassifierTrainingSessionSearchDialogFiltering(query, args);
      }
      if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public EntityRecognitionInfoSearchFilterForClassifierTrainingSession(string propertyName)
      : base(propertyName)
    {
    }
  }



  [global::Sungero.Domain.Filter(typeof(global::Sungero.Commons.Server.EntityRecognitionInfoFilter<global::Sungero.Commons.IEntityRecognitionInfo>))]
  [global::Sungero.Domain.UiFilter(typeof(global::Sungero.Commons.Server.EntityRecognitionInfoUiFilter<global::Sungero.Commons.IEntityRecognitionInfo>))]
  [global::Sungero.Domain.PropertyFilter(typeof(global::Sungero.Commons.Server.EntityRecognitionInfoFilterForClassifierTrainingSession<global::Sungero.Commons.IClassifierTrainingSession, global::Sungero.Commons.IEntityRecognitionInfo>), "ClassifierTrainingSession")]
  [global::Sungero.Domain.SearchPropertyFilter(typeof(global::Sungero.Commons.Server.EntityRecognitionInfoSearchFilterForClassifierTrainingSession<global::Sungero.Commons.IClassifierTrainingSession>), "ClassifierTrainingSession")]


  public class EntityRecognitionInfo :
    global::Sungero.CoreEntities.Server.DatabookEntry, global::Sungero.Commons.IEntityRecognitionInfo
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("32ea0857-adf7-41c2-bc0c-188320e40786");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Commons.Server.EntityRecognitionInfo.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Commons.IEntityRecognitionInfo, Sungero.Domain.Interfaces"; }
    }

    public override string DisplayValue
    {
      get { return this.Name; }
      set { this.Name = value; }
    }

    public new virtual global::Sungero.Commons.IEntityRecognitionInfoState State
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfoState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Commons.Shared.EntityRecognitionInfoState(this);
    }

    public new virtual global::Sungero.Commons.IEntityRecognitionInfoInfo Info
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfoInfo)base.Info; }
    }

    public new virtual global::Sungero.Commons.IEntityRecognitionInfoAccessRights AccessRights
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfoAccessRights)base.AccessRights; }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Commons.Server.EntityRecognitionInfoAccessRights(this);
    }

    protected override global::Sungero.Domain.EntityFunctions CreateServerFunctions()
    {
      return new global::Sungero.Commons.Server.EntityRecognitionInfoFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Commons.Shared.EntityRecognitionInfoFunctions(this);
    }

    protected override object CreateHandlers() {
      return new global::Sungero.Commons.EntityRecognitionInfoServerHandlers(this);
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.Commons.EntityRecognitionInfoSharedHandlers(this);
    }

    private global::System.String _Name;
    public virtual global::System.String Name
    {
      get
      {
        return this._Name;
      }

      set
      {
        this.SetPropertyValue("Name", this._Name, value, (propertyValue) => { this._Name = propertyValue; }, this.NameChangedHandler);
      }
    }
    private global::System.String _RecognizedClass;
    public virtual global::System.String RecognizedClass
    {
      get
      {
        return this._RecognizedClass;
      }

      set
      {
        this.SetPropertyValue("RecognizedClass", this._RecognizedClass, value, (propertyValue) => { this._RecognizedClass = propertyValue; }, this.RecognizedClassChangedHandler);
      }
    }
    private global::System.Double? _ClassProbability;
    public virtual global::System.Double? ClassProbability
    {
      get
      {
        return this._ClassProbability;
      }

      set
      {
        this.SetPropertyValue("ClassProbability", this._ClassProbability, value, (propertyValue) => { this._ClassProbability = propertyValue; }, this.ClassProbabilityChangedHandler);
      }
    }
    private global::System.Int32? _EntityId;
    public virtual global::System.Int32? EntityId
    {
      get
      {
        return this._EntityId;
      }

      set
      {
        this.SetPropertyValue("EntityId", this._EntityId, value, (propertyValue) => { this._EntityId = propertyValue; }, this.EntityIdChangedHandler);
      }
    }
    private global::System.String _EntityType;
    public virtual global::System.String EntityType
    {
      get
      {
        return this._EntityType;
      }

      set
      {
        this.SetPropertyValue("EntityType", this._EntityType, value, (propertyValue) => { this._EntityType = propertyValue; }, this.EntityTypeChangedHandler);
      }
    }
    private global::System.String _VerifiedClass;
    public virtual global::System.String VerifiedClass
    {
      get
      {
        return this._VerifiedClass;
      }

      set
      {
        this.SetPropertyValue("VerifiedClass", this._VerifiedClass, value, (propertyValue) => { this._VerifiedClass = propertyValue; }, this.VerifiedClassChangedHandler);
      }
    }
    private global::System.DateTime? _Created;
    public virtual global::System.DateTime? Created
    {
      get
      {
        return this._Created;
      }

      set
      {
        this.SetPropertyValue("Created", this._Created, value, (propertyValue) => { this._Created = propertyValue; }, this.CreatedChangedHandler);
      }
    }






    private static global::Sungero.Domain.Shared.EnumerationItems _ClassifierTrainingStatusItems = new global::Sungero.Domain.Shared.EnumerationItems(
      null,
      typeof(global::Sungero.Commons.EntityRecognitionInfo.ClassifierTrainingStatus),
      typeof(global::Sungero.Commons.Server.EntityRecognitionInfo),
      "ClassifierTrainingStatus");

    public static global::Sungero.Domain.Shared.EnumerationItems ClassifierTrainingStatusItems
    {
      get { return global::Sungero.Commons.Server.EntityRecognitionInfo._ClassifierTrainingStatusItems; }
    }

    public virtual global::Sungero.Domain.Shared.EnumerationItems ClassifierTrainingStatusAllowedItems
    {
      get { return global::Sungero.Commons.Server.EntityRecognitionInfo.ClassifierTrainingStatusItems; }
    }

    private global::Sungero.Core.Enumeration? _ClassifierTrainingStatus;

    public virtual global::Sungero.Core.Enumeration? ClassifierTrainingStatus
    {
      get { return this._ClassifierTrainingStatus; }
      set { this.SetEnumPropertyValue("ClassifierTrainingStatus", this._ClassifierTrainingStatus, value, (propertyValue) => { this._ClassifierTrainingStatus = propertyValue; }, this.ClassifierTrainingStatusChangedHandler, this.ClassifierTrainingStatusAllowedItems); }
    }


    private global::Sungero.Commons.IClassifierTrainingSession _ClassifierTrainingSession;
    public virtual global::Sungero.Commons.IClassifierTrainingSession ClassifierTrainingSession
    {
      get
      {
        return this._ClassifierTrainingSession;
      }

      set
      {
        this.SetPropertyValue("ClassifierTrainingSession", this._ClassifierTrainingSession, value, (propertyValue) => { this._ClassifierTrainingSession = propertyValue; }, this.ClassifierTrainingSessionChangedHandler);
      }
    }


    protected global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoFacts> _Facts;

    public virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoFacts> Facts
    {
      get
      {
        if (this._Facts == null)
        {
          this._Facts = this.CreateFactsCollection();
          this.SetFactsEventHandlers();
        }
        return this._Facts;
      }

      set
      {
        if (this._Facts != null)
          this.UnsetChildCollectionEventHandlers(this._Facts);

        this._Facts = value;
        this.SetFactsEventHandlers();
      }
    }

    protected virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoFacts> CreateFactsCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoFacts>() { RootEntity = this };
    }

    private void SetFactsEventHandlers()
    {
      this.SetChildCollectionEventHandlers(this._Facts, "Facts");

      var changeNotifier = (global::Sungero.Domain.Shared.INotifyChildEntityCollectionChanged)this._Facts;
      changeNotifier.Added += this.FactsAddedHandler;
      changeNotifier.Deleted += this.FactsDeletedHandler;
      changeNotifier.Added += this.FactsCollectionUpdateEventHandler;
      changeNotifier.Deleted += this.FactsCollectionUpdateEventHandler;
      changeNotifier.Updated += this.FactsCollectionUpdateEventHandler;
    }

    private void FactsCollectionUpdateEventHandler(object sender, global::Sungero.Domain.Shared.BaseChildEntityEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      if (this.IsPropertyChangedHandlerEnabled && this.IsPropertyChangedAppliedHandlerEnabled("Facts"))
        this.FactsChangedHandler();
    }
    protected global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoAdditionalClassifiers> _AdditionalClassifiers;

    public virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoAdditionalClassifiers> AdditionalClassifiers
    {
      get
      {
        if (this._AdditionalClassifiers == null)
        {
          this._AdditionalClassifiers = this.CreateAdditionalClassifiersCollection();
          this.SetAdditionalClassifiersEventHandlers();
        }
        return this._AdditionalClassifiers;
      }

      set
      {
        if (this._AdditionalClassifiers != null)
          this.UnsetChildCollectionEventHandlers(this._AdditionalClassifiers);

        this._AdditionalClassifiers = value;
        this.SetAdditionalClassifiersEventHandlers();
      }
    }

    protected virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoAdditionalClassifiers> CreateAdditionalClassifiersCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::Sungero.Commons.IEntityRecognitionInfoAdditionalClassifiers>() { RootEntity = this };
    }

    private void SetAdditionalClassifiersEventHandlers()
    {
      this.SetChildCollectionEventHandlers(this._AdditionalClassifiers, "AdditionalClassifiers");

      var changeNotifier = (global::Sungero.Domain.Shared.INotifyChildEntityCollectionChanged)this._AdditionalClassifiers;
      changeNotifier.Added += this.AdditionalClassifiersAddedHandler;
      changeNotifier.Deleted += this.AdditionalClassifiersDeletedHandler;
      changeNotifier.Added += this.AdditionalClassifiersCollectionUpdateEventHandler;
      changeNotifier.Deleted += this.AdditionalClassifiersCollectionUpdateEventHandler;
      changeNotifier.Updated += this.AdditionalClassifiersCollectionUpdateEventHandler;
    }

    private void AdditionalClassifiersCollectionUpdateEventHandler(object sender, global::Sungero.Domain.Shared.BaseChildEntityEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      if (this.IsPropertyChangedHandlerEnabled && this.IsPropertyChangedAppliedHandlerEnabled("AdditionalClassifiers"))
        this.AdditionalClassifiersChangedHandler();
    }



    protected override global::Sungero.Domain.Shared.EntityCreatingFromServerHandler CreateCreatingFromServerHandler(
      global::Sungero.Domain.Shared.IEntity entitySource)
    {
      var instance = Sungero.Metadata.Services.AppliedTypesManager.CreateInstance("Sungero.Commons.EntityRecognitionInfoCreatingFromServerHandler", new object[] { (global::Sungero.Commons.IEntityRecognitionInfo)entitySource, this.Info });
      if (instance != null)
        return (global::Sungero.Domain.Shared.EntityCreatingFromServerHandler)instance;

      return new global::Sungero.Commons.EntityRecognitionInfoCreatingFromServerHandler((global::Sungero.Commons.IEntityRecognitionInfo)entitySource, this.Info);
    }

    #region Framework events

    protected void NameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.Name, this.Name, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).NameChanged(args);
    }

    protected void RecognizedClassChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.RecognizedClass, this.RecognizedClass, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).RecognizedClassChanged(args);
    }

    protected void ClassProbabilityChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.DoublePropertyChangedEventArgs(this.State.Properties.ClassProbability, this.ClassProbability, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).ClassProbabilityChanged(args);
    }

    protected void EntityIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.EntityId, this.EntityId, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).EntityIdChanged(args);
    }

    protected void EntityTypeChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.EntityType, this.EntityType, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).EntityTypeChanged(args);
    }

    protected void FactsChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).FactsChanged(args);
    }

    protected void AdditionalClassifiersChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).AdditionalClassifiersChanged(args);
    }

    protected void ClassifierTrainingStatusChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.EnumerationPropertyChangedEventArgs(this.State.Properties.ClassifierTrainingStatus, this.ClassifierTrainingStatus, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).ClassifierTrainingStatusChanged(args);
    }

    protected void ClassifierTrainingSessionChangedHandler()
    {
      var args = new global::Sungero.Commons.Shared.EntityRecognitionInfoClassifierTrainingSessionChangedEventArgs(this.State.Properties.ClassifierTrainingSession, this.ClassifierTrainingSession, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).ClassifierTrainingSessionChanged(args);
    }

    protected void VerifiedClassChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.VerifiedClass, this.VerifiedClass, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).VerifiedClassChanged(args);
    }

    protected void CreatedChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.DateTimePropertyChangedEventArgs(this.State.Properties.Created, this.Created, this);
     ((global::Sungero.Commons.IEntityRecognitionInfoSharedHandlers)this.SharedHandlers).CreatedChanged(args);
    }



    protected virtual global::Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers CreateFactsAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers CreateFactsDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void FactsAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, e.Value, null, e.Source });
        var methodInfo = type.GetMethod("FactsAdded");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateFactsAddedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
          collectionHandlers.FactsAdded(args);
        }
      }
    }

    protected virtual void FactsDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoFactsSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, null, e.Value, null });
        var methodInfo = type.GetMethod("FactsDeleted");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateFactsDeletedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
          collectionHandlers.FactsDeleted(args);
        }
      }
    }


    protected virtual global::Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers CreateAdditionalClassifiersAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers CreateAdditionalClassifiersDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void AdditionalClassifiersAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, e.Value, null, e.Source });
        var methodInfo = type.GetMethod("AdditionalClassifiersAdded");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateAdditionalClassifiersAddedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
          collectionHandlers.AdditionalClassifiersAdded(args);
        }
      }
    }

    protected virtual void AdditionalClassifiersDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.EntityRecognitionInfoAdditionalClassifiersSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, null, e.Value, null });
        var methodInfo = type.GetMethod("AdditionalClassifiersDeleted");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateAdditionalClassifiersDeletedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
          collectionHandlers.AdditionalClassifiersDeleted(args);
        }
      }
    }


    #endregion


    public EntityRecognitionInfo()
    {
    }

  }
}

// ==================================================================
// EntityRecognitionInfoHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons
{
  public partial class EntityRecognitionInfoClassifierTrainingSessionPropertyFilteringServerHandler<T>
    : global::Sungero.Domain.EntityPropertyFilteringServerHandler
    where T : class, global::Sungero.Commons.IClassifierTrainingSession
  {
    private global::Sungero.Commons.IEntityRecognitionInfo _obj
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfo)this.Entity; }
    }

    public virtual global::System.Linq.IQueryable<T> ClassifierTrainingSessionFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertyFilteringEventArgs e)
    {
      return query;
    }

    public EntityRecognitionInfoClassifierTrainingSessionPropertyFilteringServerHandler(global::Sungero.Commons.IEntityRecognitionInfo entity)
      : base(entity)
    {
    }
  }

  public partial class EntityRecognitionInfoClassifierTrainingSessionSearchPropertyFilteringServerHandler<T>
    : global::Sungero.Domain.SearchPropertyFilteringServerHandler
    where T : class, global::Sungero.Commons.IClassifierTrainingSession
  {

    public virtual global::System.Linq.IQueryable<T> ClassifierTrainingSessionSearchDialogFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertySearchDialogFilteringEventArgs e)
    {
      return query;
    }

    public EntityRecognitionInfoClassifierTrainingSessionSearchPropertyFilteringServerHandler()
      : base()
    {
    }
  }



  public partial class EntityRecognitionInfoFilteringServerHandler<T>
    : global::Sungero.Domain.EntityFilteringServerHandler<T>  
    where T : class, global::Sungero.Commons.IEntityRecognitionInfo
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected new global::Sungero.Commons.IEntityRecognitionInfoFilterState Filter { get; private set; }

    private global::Sungero.Commons.IEntityRecognitionInfoFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public EntityRecognitionInfoFilteringServerHandler(global::Sungero.Commons.IEntityRecognitionInfoFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected EntityRecognitionInfoFilteringServerHandler()
    {
    }

    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.FilteringEventArgs e)
    {
      return query;
    }


  }

  public partial class EntityRecognitionInfoUiFilteringServerHandler<T>
    : global::Sungero.Domain.EntityUiFilteringServerHandler<T>
    where T : class, global::Sungero.Commons.IEntityRecognitionInfo
  {
    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.UiFilteringEventArgs e)
    {
      query = base.Filtering(query, e);
            return query;
    }
  }

  public partial class EntityRecognitionInfoSearchDialogServerHandler : global::Sungero.CoreEntities.DatabookEntrySearchDialogServerHandler
   {
     private global::Sungero.Commons.Server.EntityRecognitionInfoSearchDialogModel _dialog
     {
       get
       {
         return (global::Sungero.Commons.Server.EntityRecognitionInfoSearchDialogModel)this.Dialog;
       }
     }

     public EntityRecognitionInfoSearchDialogServerHandler(global::Sungero.Commons.Server.EntityRecognitionInfoSearchDialogModel dialog)
       : base(dialog)
     {
     }
   }

  public partial class EntityRecognitionInfoServerHandlers : global::Sungero.CoreEntities.DatabookEntryServerHandlers
  {
    private global::Sungero.Commons.IEntityRecognitionInfo _obj
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfo)this.Entity; }
    }

    public EntityRecognitionInfoServerHandlers(global::Sungero.Commons.IEntityRecognitionInfo entity)
      : base(entity)
    {
    }
  }

  public partial class EntityRecognitionInfoCreatingFromServerHandler : global::Sungero.CoreEntities.DatabookEntryCreatingFromServerHandler
  {
    private global::Sungero.Commons.IEntityRecognitionInfo _source
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfo)this.Source; }
    }

    private global::Sungero.Commons.IEntityRecognitionInfoInfo _info
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfoInfo)this._Info; }
    }

    public EntityRecognitionInfoCreatingFromServerHandler(global::Sungero.Commons.IEntityRecognitionInfo source, global::Sungero.Commons.IEntityRecognitionInfoInfo info)
      : base(source, info)
    {
    }
  }

}

// ==================================================================
// EntityRecognitionInfoEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
}

// ==================================================================
// EntityRecognitionInfoAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
  public class EntityRecognitionInfoAccessRights : 
    Sungero.CoreEntities.Server.DatabookEntryAccessRights, Sungero.Commons.IEntityRecognitionInfoAccessRights
  {

    public EntityRecognitionInfoAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class EntityRecognitionInfoTypeAccessRights : 
    Sungero.CoreEntities.Server.DatabookEntryTypeAccessRights, Sungero.Commons.IEntityRecognitionInfoAccessRights
  {

    public EntityRecognitionInfoTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}

// ==================================================================
// EntityRecognitionInfoRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
    public class EntityRecognitionInfoRepositoryImplementer<T> : 
      global::Sungero.Domain.RepositoryImplementer<T>,
      global::Sungero.Commons.IEntityRecognitionInfoRepositoryImplementer<T>
      where T : global::Sungero.Commons.IEntityRecognitionInfo 
    {
       public new global::Sungero.Commons.IEntityRecognitionInfoAccessRights AccessRights
       {
          get { return (global::Sungero.Commons.IEntityRecognitionInfoAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Commons.IEntityRecognitionInfoInfo Info
       {
          get { return (global::Sungero.Commons.IEntityRecognitionInfoInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Commons.Server.EntityRecognitionInfoTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// EntityRecognitionInfoPanelNavigationFilters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
}

// ==================================================================
// EntityRecognitionInfoServerFunctions.g.cs
// ==================================================================

namespace Sungero.Commons.Server
{
  public partial class EntityRecognitionInfoFunctions : global::Sungero.CoreEntities.Server.DatabookEntryFunctions
  {
    private global::Sungero.Commons.IEntityRecognitionInfo _obj
    {
      get { return (global::Sungero.Commons.IEntityRecognitionInfo)this.Entity; }
    }

    public EntityRecognitionInfoFunctions(global::Sungero.Commons.IEntityRecognitionInfo entity) : base(entity) { }
  }
}

// ==================================================================
// EntityRecognitionInfoFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Functions
{
  internal static class EntityRecognitionInfo
  {
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  global::Sungero.Commons.IEntityRecognitionInfo GetEntityRecognitionInfo(global::Sungero.Domain.Shared.IEntity entity)
    {
      var __funcType = Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.Commons.Server.EntityRecognitionInfoFunctions");
      if (__funcType != null)
      {    
        var __funcMethod = __funcType.GetMethod("GetEntityRecognitionInfo",
          System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic,
          null, new System.Type[] { typeof(global::Sungero.Domain.Shared.IEntity) }, null);
        return (global::Sungero.Commons.IEntityRecognitionInfo)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, null, new object[] { entity });
      }
      else
      {
        return global::Sungero.Commons.Server.EntityRecognitionInfoFunctions.GetEntityRecognitionInfo(entity);
      }
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static  void Clone(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Domain.Shared.IEntity targetEntity)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("Clone", new System.Type[] { typeof(global::Sungero.Domain.Shared.IEntity) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { targetEntity });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  global::System.Nullable<global::System.Double> GetProbabilityByPropertyName(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::System.String propertyName)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetProbabilityByPropertyName", new System.Type[] { typeof(global::System.String) });
      return (global::System.Nullable<global::System.Double>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { propertyName });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("LinkFactAndProperty", new System.Type[] { typeof(global::Sungero.Commons.Structures.Module.IArioFact), typeof(global::System.String), typeof(global::System.String), typeof(System.Object) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { fact, fieldName, propertyName, propertyValue });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("LinkFactAndProperty", new System.Type[] { typeof(global::Sungero.Commons.Structures.Module.IArioFact), typeof(global::System.String), typeof(global::System.String), typeof(System.Object), typeof(global::System.Nullable<global::System.Double>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { fact, fieldName, propertyName, propertyValue, probability });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability, global::System.Nullable<global::System.Int32> collectionRecordId)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("LinkFactAndProperty", new System.Type[] { typeof(global::Sungero.Commons.Structures.Module.IArioFact), typeof(global::System.String), typeof(global::System.String), typeof(System.Object), typeof(global::System.Nullable<global::System.Double>), typeof(global::System.Nullable<global::System.Int32>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { fact, fieldName, propertyName, propertyValue, probability, collectionRecordId });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  void LinkFactFieldsAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.Collections.Generic.List<global::System.String> fieldNames, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability, global::System.Nullable<global::System.Int32> collectionRecordId)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("LinkFactFieldsAndProperty", new System.Type[] { typeof(global::Sungero.Commons.Structures.Module.IArioFact), typeof(global::System.Collections.Generic.List<global::System.String>), typeof(global::System.String), typeof(System.Object), typeof(global::System.Nullable<global::System.Double>), typeof(global::System.Nullable<global::System.Int32>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { fact, fieldNames, propertyName, propertyValue, probability, collectionRecordId });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  global::Sungero.Domain.Shared.IEntity GetDocument(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDocument", new System.Type[] {  });
      return (global::Sungero.Domain.Shared.IEntity)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  global::System.Collections.Generic.List<global::System.Int32> UpdatePagesInPositions(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, System.Collections.Generic.IDictionary<global::System.String, global::System.String> newPagesOrder)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("UpdatePagesInPositions", new System.Type[] { typeof(System.Collections.Generic.IDictionary<global::System.String, global::System.String>) });
      return (global::System.Collections.Generic.List<global::System.Int32>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { newPagesOrder });
    }
    /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.EntityRecognitionInfoFunctions" />
    internal static  void ClearFactAndPropertyLink(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::System.Collections.Generic.List<global::System.Int32> factsIds)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)entityRecognitionInfo).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ClearFactAndPropertyLink", new System.Type[] { typeof(global::System.Collections.Generic.List<global::System.Int32>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { factsIds });
    }

  }
}

// ==================================================================
// EntityRecognitionInfoServerPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Server
{
  public class EntityRecognitionInfoServerPublicFunctions : global::Sungero.Commons.Server.IEntityRecognitionInfoServerPublicFunctions
  {
    public void ClearFactAndPropertyLink(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::System.Collections.Generic.List<global::System.Int32> factsIds)
    {
global::Sungero.Commons.Functions.EntityRecognitionInfo.ClearFactAndPropertyLink(entityRecognitionInfo, factsIds);
    }
    public global::System.Nullable<global::System.Double> GetProbabilityByPropertyName(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::System.String propertyName)
    {
      return global::Sungero.Commons.Functions.EntityRecognitionInfo.GetProbabilityByPropertyName(entityRecognitionInfo, propertyName);
    }
    public void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue)
    {
global::Sungero.Commons.Functions.EntityRecognitionInfo.LinkFactAndProperty(entityRecognitionInfo, fact, fieldName, propertyName, propertyValue);
    }
    public void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability)
    {
global::Sungero.Commons.Functions.EntityRecognitionInfo.LinkFactAndProperty(entityRecognitionInfo, fact, fieldName, propertyName, propertyValue, probability);
    }
    public void LinkFactAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.String fieldName, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability, global::System.Nullable<global::System.Int32> collectionRecordId)
    {
global::Sungero.Commons.Functions.EntityRecognitionInfo.LinkFactAndProperty(entityRecognitionInfo, fact, fieldName, propertyName, propertyValue, probability, collectionRecordId);
    }
    public void LinkFactFieldsAndProperty(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, global::Sungero.Commons.Structures.Module.IArioFact fact, global::System.Collections.Generic.List<global::System.String> fieldNames, global::System.String propertyName, System.Object propertyValue, global::System.Nullable<global::System.Double> probability, global::System.Nullable<global::System.Int32> collectionRecordId)
    {
global::Sungero.Commons.Functions.EntityRecognitionInfo.LinkFactFieldsAndProperty(entityRecognitionInfo, fact, fieldNames, propertyName, propertyValue, probability, collectionRecordId);
    }
    public global::System.Collections.Generic.List<global::System.Int32> UpdatePagesInPositions(global::Sungero.Commons.IEntityRecognitionInfo entityRecognitionInfo, System.Collections.Generic.IDictionary<global::System.String, global::System.String> newPagesOrder)
    {
      return global::Sungero.Commons.Functions.EntityRecognitionInfo.UpdatePagesInPositions(entityRecognitionInfo, newPagesOrder);
    }
  }
}

// ==================================================================
// EntityRecognitionInfoQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Queries
{
  public class EntityRecognitionInfo
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.Commons.Server.EntityRecognitionInfo.EntityRecognitionInfoQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}
