
// ==================================================================
// FormalizedPowerOfAttorneyState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FormalizedPowerOfAttorneyState : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBaseState, global::Sungero.Docflow.IFormalizedPowerOfAttorneyState
  {
    public FormalizedPowerOfAttorneyState(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity) { }

    public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyPropertyStates(entity);
    }


    public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyControlStates Controls
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyControlStates(entity);
    }

    public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyPageStates Pages
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyPageStates(entity);
    }

  }


  public class FormalizedPowerOfAttorneyControlStates : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBaseControlStates, global::Sungero.Docflow.IFormalizedPowerOfAttorneyControlStates
  {

    protected internal FormalizedPowerOfAttorneyControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class FormalizedPowerOfAttorneyPageStates : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBasePageStates, global::Sungero.Docflow.IFormalizedPowerOfAttorneyPageStates
  {

    protected internal FormalizedPowerOfAttorneyPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class FormalizedPowerOfAttorneyPropertyStates : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBasePropertyStates, global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertyStates
  {
            public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersionsCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions> Versions
            {
              get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersionsCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>)base.Versions; }
            }

            protected override global::Sungero.Content.IElectronicDocumentVersionsCollectionPropertyState<global::Sungero.Content.IElectronicDocumentVersions> CreateVersionsState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyVersionsCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersions>(entity, propertyName);
            }
            public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyTrackingCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTracking> Tracking
            {
              get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyTrackingCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTracking>)base.Tracking; }
            }

            protected override global::Sungero.Docflow.IOfficialDocumentTrackingCollectionPropertyState<global::Sungero.Docflow.IOfficialDocumentTracking> CreateTrackingState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyTrackingCollectionPropertyState<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTracking>(entity, propertyName);
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> UnifiedRegistrationNumber 
            {
              get { return this.GetPropertyState<global::System.String>("UnifiedRegistrationNumber"); }
            }


    protected internal FormalizedPowerOfAttorneyPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// FormalizedPowerOfAttorneyInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FormalizedPowerOfAttorneyInfo : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBaseInfo, global::Sungero.Docflow.IFormalizedPowerOfAttorneyInfo
  {
    public FormalizedPowerOfAttorneyInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertiesInfo Properties
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertiesInfo)base.Properties; }
    }

    public new global::Sungero.Docflow.IFormalizedPowerOfAttorneyActionsInfo Actions
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorneyActionsInfo)base.Actions; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyPropertiesInfo(entityType);
    }

    protected override global::Sungero.Domain.Shared.IEntityActionsInfo CreateEntityActionsInfo(global::System.Type entityType)
    {
      return new global::Sungero.Docflow.Shared.FormalizedPowerOfAttorneyActionsInfo(entityType);
    }
  }

  public class FormalizedPowerOfAttorneyPropertiesInfo : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBasePropertiesInfo, global::Sungero.Docflow.IFormalizedPowerOfAttorneyPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersionsPropertiesInfo> Versions
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Versions");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFormalizedPowerOfAttorneyVersionsPropertiesInfo>(propertyMetadata);
          }
        }
        public new global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTrackingPropertiesInfo> Tracking
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Tracking");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFormalizedPowerOfAttorneyTrackingPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IStringPropertyInfo UnifiedRegistrationNumber 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("UnifiedRegistrationNumber");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }


    protected internal FormalizedPowerOfAttorneyPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

  public class FormalizedPowerOfAttorneyActionsInfo : 
    global::Sungero.Docflow.Shared.PowerOfAttorneyBaseActionsInfo, global::Sungero.Docflow.IFormalizedPowerOfAttorneyActionsInfo
  {
        public global::Sungero.Domain.Shared.IActionInfo ImportVersionWithSignature 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ImportVersionWithSignature")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo ShowDuplicates 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ShowDuplicates")); }
        }


    protected internal FormalizedPowerOfAttorneyActionsInfo(global::System.Type entityType) : base(entityType) { }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{
  public partial class FormalizedPowerOfAttorneySharedHandlers : global::Sungero.Docflow.PowerOfAttorneyBaseSharedHandlers, IFormalizedPowerOfAttorneySharedHandlers
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }


    public FormalizedPowerOfAttorneySharedHandlers(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// FormalizedPowerOfAttorneyResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared.FormalizedPowerOfAttorney
{
  /// <summary>
  /// Represents FormalizedPowerOfAttorney resources.
  /// </summary>
  public class FormalizedPowerOfAttorneyResources : global::Sungero.Docflow.Shared.PowerOfAttorneyBase.PowerOfAttorneyBaseResources, global::Sungero.Docflow.FormalizedPowerOfAttorney.IFormalizedPowerOfAttorneyResources
  {
    public virtual global::CommonLibrary.LocalizedString ErrorValidateUnifiedRegistrationNumber
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "ErrorValidateUnifiedRegistrationNumber");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ErrorValidateUnifiedRegistrationNumberFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "ErrorValidateUnifiedRegistrationNumber", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RegistrationNumberInBrackets
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "RegistrationNumberInBrackets");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RegistrationNumberInBracketsFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "RegistrationNumberInBrackets", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString UnifiedRegistrationNumber
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "UnifiedRegistrationNumber");
      }
    }

    public virtual global::CommonLibrary.LocalizedString UnifiedRegistrationNumberFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "UnifiedRegistrationNumber", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ImportPowerOfAttorneyFromXml
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "ImportPowerOfAttorneyFromXml");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ImportPowerOfAttorneyFromXmlFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "ImportPowerOfAttorneyFromXml", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString File
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "File");
      }
    }

    public virtual global::CommonLibrary.LocalizedString FileFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "File", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SignatureFile
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "SignatureFile");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SignatureFileFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "SignatureFile", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Import
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "Import");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ImportFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "Import", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString FormalizedPowerOfAttorneyImportFailed
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "FormalizedPowerOfAttorneyImportFailed");
      }
    }

    public virtual global::CommonLibrary.LocalizedString FormalizedPowerOfAttorneyImportFailedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "FormalizedPowerOfAttorneyImportFailed", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString XmlLoadFailed
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "XmlLoadFailed");
      }
    }

    public virtual global::CommonLibrary.LocalizedString XmlLoadFailedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "XmlLoadFailed", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SignatureImportFailed
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "SignatureImportFailed");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SignatureImportFailedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "SignatureImportFailed", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString PowerOfAttorneySuccessfullyImported
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "PowerOfAttorneySuccessfullyImported");
      }
    }

    public virtual global::CommonLibrary.LocalizedString PowerOfAttorneySuccessfullyImportedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "PowerOfAttorneySuccessfullyImported", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Enum_Operation_ImportFromXml
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "Enum_Operation_ImportFromXml");
      }
    }

    public virtual global::CommonLibrary.LocalizedString Enum_Operation_ImportFromXmlFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "Enum_Operation_ImportFromXml", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ImportFromXmlHistoryComment
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "ImportFromXmlHistoryComment");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ImportFromXmlHistoryCommentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "ImportFromXmlHistoryComment", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DuplicatesNotFound
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "DuplicatesNotFound");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DuplicatesNotFoundFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "DuplicatesNotFound", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DuplicatesDetected
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "DuplicatesDetected");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DuplicatesDetectedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "DuplicatesDetected", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString FormalizedPowerOfAttorney
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney) , "FormalizedPowerOfAttorney");
      }
    }

    public virtual global::CommonLibrary.LocalizedString FormalizedPowerOfAttorneyFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFormalizedPowerOfAttorney), "FormalizedPowerOfAttorney", false, args);
    }

  }
}

// ==================================================================
// FormalizedPowerOfAttorneySharedFunctions.g.cs
// ==================================================================

namespace Sungero.Docflow.Shared
{
  public partial class FormalizedPowerOfAttorneyFunctions : global::Sungero.Docflow.Shared.PowerOfAttorneyBaseFunctions
  {
    private global::Sungero.Docflow.IFormalizedPowerOfAttorney _obj
    {
      get { return (global::Sungero.Docflow.IFormalizedPowerOfAttorney)this.Entity; }
    }

    public FormalizedPowerOfAttorneyFunctions(global::Sungero.Docflow.IFormalizedPowerOfAttorney entity) : base(entity) { }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Functions
{
  internal static class FormalizedPowerOfAttorney
  {
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeRegistrationPaneVisibility(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean needShow, global::System.Boolean repeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeRegistrationPaneVisibility", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { needShow, repeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetActiveLifeCycleState(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetActiveLifeCycleState", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Boolean CheckRegistrationNumberUnique(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("CheckRegistrationNumberUnique", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void FillName(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("FillName", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void ChangeDocumentPropertiesAccess(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::System.Boolean isEnabled, global::System.Boolean isRepeatRegister)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ChangeDocumentPropertiesAccess", new System.Type[] { typeof(global::System.Boolean), typeof(global::System.Boolean) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { isEnabled, isRepeatRegister });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  void SetRequiredProperties(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.String GetDuplicatesErrorText(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicatesErrorText", new System.Type[] {  });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FormalizedPowerOfAttorneyFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)formalizedPowerOfAttorney).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetDuplicates", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    internal static class Remote
    {
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
      internal static  void ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
      {
      global::Sungero.Domain.Shared.RemoteFunctionExecutor.Execute(
          global::System.Guid.Parse("104472db-b71b-42a8-bca5-581a08d1ca7b"),
          "ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney,global::Sungero.Docflow.Structures.Module.IByteArray,global::Sungero.Docflow.Structures.Module.IByteArray)"
          , formalizedPowerOfAttorney, xml, signature);
      }
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FormalizedPowerOfAttorneyFunctions" />
      internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney>>(
          global::System.Guid.Parse("104472db-b71b-42a8-bca5-581a08d1ca7b"),
          "GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney)"
          , formalizedPowerOfAttorney);
      }

    }
  }
}

// ==================================================================
// FormalizedPowerOfAttorneyFilterState.g.cs
// ==================================================================

namespace Sungero.Docflow.Shared.FormalizedPowerOfAttorney
{

  public class FormalizedPowerOfAttorneyFilterInfo : global::Sungero.Docflow.Shared.PowerOfAttorneyBase.PowerOfAttorneyBaseFilterInfo,
    global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterInfo
  {
  }

  public class FormalizedPowerOfAttorneyFilterState : global::Sungero.Docflow.Shared.PowerOfAttorneyBase.PowerOfAttorneyBaseFilterState,
    global::Sungero.Docflow.IFormalizedPowerOfAttorneyFilterState
  {



    public new Sungero.Docflow.IFormalizedPowerOfAttorneyFilterInfo Info
    {
      get
      {
        return (Sungero.Docflow.IFormalizedPowerOfAttorneyFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new Sungero.Docflow.Shared.FormalizedPowerOfAttorney.FormalizedPowerOfAttorneyFilterInfo();
    }

  }
}

// ==================================================================
// FormalizedPowerOfAttorneySharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FormalizedPowerOfAttorneySharedPublicFunctions : global::Sungero.Docflow.Shared.IFormalizedPowerOfAttorneySharedPublicFunctions
  {
    public global::System.Collections.Generic.List<global::Sungero.Docflow.IFormalizedPowerOfAttorney> Remote_GetFormalizedPowerOfAttorneyDuplicates(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
      return global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.Remote.GetFormalizedPowerOfAttorneyDuplicates(formalizedPowerOfAttorney);
    }
    public void Remote_ImportFormalizedPowerOfAttorneyFromXmlAndSign(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney, global::Sungero.Docflow.Structures.Module.IByteArray xml, global::Sungero.Docflow.Structures.Module.IByteArray signature)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.Remote.ImportFormalizedPowerOfAttorneyFromXmlAndSign(formalizedPowerOfAttorney, xml, signature);
    }
    public void SetActiveLifeCycleState(global::Sungero.Docflow.IFormalizedPowerOfAttorney formalizedPowerOfAttorney)
    {
global::Sungero.Docflow.Functions.FormalizedPowerOfAttorney.SetActiveLifeCycleState(formalizedPowerOfAttorney);
    }
  }
}
