//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  /// <summary>
  /// Interaction logic for VATRateView.xaml.
  /// </summary>
  public partial class VATRateView : global::System.Windows.Controls.UserControl
  {
    public VATRateView()
    {
      InitializeComponent();
      global::CommonLibrary.Controls.Utils.WindowHelper.SubscribeToEventUpdateSizeLayoutGridsColumns(this);
    }
  }
}