
// ==================================================================
// VATRate.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class VATRate :
    global::Sungero.CoreEntities.Client.DatabookEntry, global::Sungero.Commons.IVATRate
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("fe0ed345-5965-40d6-a559-24dcde189a95");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Commons.Client.VATRate.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Commons.IVATRate, Sungero.Domain.Interfaces"; }
    }

      public override string DisplayValue
      {
        get { return this.Name; }
        set { this.Name = value; }
      }

      public override string DisplayPropertyName
      {
        get { return "Name"; }
      }


    public new global::Sungero.Commons.IVATRateState State
    {
      get
      {
        return (global::Sungero.Commons.IVATRateState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Commons.Shared.VATRateState(this);
    }

    public new global::Sungero.Commons.IVATRateInfo Info
    {
      get
      {
        return (global::Sungero.Commons.IVATRateInfo)base.Info;
      }
    }

    public new global::Sungero.Commons.IVATRateAccessRights AccessRights
    {
      get
      {
        return (global::Sungero.Commons.IVATRateAccessRights)base.AccessRights;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Commons.Client.VATRateAccessRights(this);
    }

        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _Name;

        public virtual global::System.String Name
        {
          get { return this._Name.Value; }
          set { this._Name.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?> _Rate;

        public virtual global::System.Int32? Rate
        {
          get { return this._Rate.Value; }
          set { this._Rate.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _Sid;

        public virtual global::System.String Sid
        {
          get { return this._Sid.Value; }
          set { this._Sid.Value = value; }
        }










    #endregion

    #region Methods

    protected override object CreateActionsHandlers()
    {
      return new global::Sungero.Commons.Client.VATRateActions(this);
    }

    protected override object CreateCollectionActionsHandlers()
    {
      return new global::Sungero.Commons.Client.VATRateCollectionActions();
    }

    protected override object CreateAnyChildEntityActionsHandlers()
    {
      return new global::Sungero.Commons.Client.VATRateAnyChildEntityActions();
    }

    protected override object CreateAnyChildEntityCollectionActionsHandlers()
    {
      return new global::Sungero.Commons.Client.VATRateAnyChildEntityCollectionActions();
    }


    protected override global::Sungero.Domain.Client.EntityFunctions CreateClientFunctions()
    {
      return new global::Sungero.Commons.Client.VATRateFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Commons.Shared.VATRateFunctions(this);
    }
    protected override object CreateHandlers() {
      return new global::Sungero.Commons.VATRateClientHandlers(this);
    }
    protected override object CreateSharedHandlers() {
      return new global::Sungero.Commons.VATRateSharedHandlers(this);
    }

    #endregion

    #region Framework events

    protected void NameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.Name, this.Name, this);
     ((global::Sungero.Commons.IVATRateSharedHandlers)this.SharedHandlers).NameChanged(args);
    }

    protected void RateChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.Rate, this.Rate, this);
     ((global::Sungero.Commons.IVATRateSharedHandlers)this.SharedHandlers).RateChanged(args);
    }

    protected void SidChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.Sid, this.Sid, this);
     ((global::Sungero.Commons.IVATRateSharedHandlers)this.SharedHandlers).SidChanged(args);
    }



  protected global::System.String NameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.Name, value, this, this.Info.Properties.Name);
    ((global::Sungero.Commons.VATRateClientHandlers)this.Handlers).NameValueInput(args);
    return args.NewValue;
  }

  protected global::System.Int32? RateValueInputHandler(global::System.Int32? value)
  {
    var args = new global::Sungero.Presentation.IntegerValueInputEventArgs(this.Rate, value, this, this.Info.Properties.Rate);
    ((global::Sungero.Commons.VATRateClientHandlers)this.Handlers).RateValueInput(args);
    return args.NewValue;
  }

  protected global::System.String SidValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.Sid, value, this, this.Info.Properties.Sid);
    ((global::Sungero.Commons.VATRateClientHandlers)this.Handlers).SidValueInput(args);
    return args.NewValue;
  }



    #endregion

    #region Constructors



    public VATRate()
    {
            this._Name = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("Name", this);
            this._Name.ValueChanged += (sender, e) => { this.NameChangedHandler(); };
            this.AddProperty(this._Name);

            this._Rate = new global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?>("Rate", this);
            this._Rate.ValueChanged += (sender, e) => { this.RateChangedHandler(); };
            this.AddProperty(this._Rate);

            this._Sid = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("Sid", this);
            this._Sid.ValueChanged += (sender, e) => { this.SidChangedHandler(); };
            this.AddProperty(this._Sid);








    }

    #endregion

  }
}

// ==================================================================
// VATRatePresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class VATRatePresenter<T> :
    global::Sungero.Domain.Client.EntityPresenter<T>
    where T : class, global::Sungero.Commons.IVATRate
  {
    #region Fields and properties




    #endregion

    #region Methods


    #endregion

    #region Framework events

    protected override void EntityPropertyChangedEventHandler(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)
    {
      base.EntityPropertyChangedEventHandler(sender, e);
    }

    #endregion



    #region Constructors

    private void Init()
    {

    }

    public VATRatePresenter()
    {
      this.Init();
    }

    #endregion
  }
}

// ==================================================================
// VATRateCollectionPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class VATRateCollectionPresenter<T> : 
    global::Sungero.Domain.Client.EntityCollectionPresenter<T>
    where T: class, global::Sungero.Commons.IVATRate
  {
    #region Actions



    #endregion

    #region Methods


    #endregion

    public VATRateCollectionPresenter(global::System.Linq.IQueryable<T> query, OnLookup onLookup)
      : base(query, onLookup)
    {
    }

    public VATRateCollectionPresenter(global::System.Linq.IQueryable<T> query)
      : this(query, null) { }

    public VATRateCollectionPresenter(OnLookup onLookup)
      : this(null, onLookup) { }

    public VATRateCollectionPresenter()
      : this(null, null) { }
  }
}

// ==================================================================
// VATRateRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{ 
  public class VATRateRepositoryImplementer<T> : 
      global::Sungero.Domain.Client.RepositoryImplementer<T>,
      global::Sungero.Commons.IVATRateRepositoryImplementer<T>
      where T : global::Sungero.Commons.IVATRate
    {
       public new global::Sungero.Commons.IVATRateAccessRights AccessRights
       {
          get { return (global::Sungero.Commons.IVATRateAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Commons.IVATRateInfo Info
       {
          get { return (global::Sungero.Commons.IVATRateInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Commons.Client.VATRateTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// VATRateAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class VATRateAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryAccessRights, Sungero.Commons.IVATRateAccessRights
  {

    public VATRateAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class VATRateTypeAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryTypeAccessRights, Sungero.Commons.IVATRateAccessRights
  {

    public VATRateTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}
