
// ==================================================================
// VATRateEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{ 
}

// ==================================================================
// VATRateHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons
{

  public partial class VATRateFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.Commons.IVATRateFilterState Filter { get; private set; }

    private global::Sungero.Commons.IVATRateFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public VATRateFilteringClientHandler(global::Sungero.Commons.IVATRateFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected VATRateFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class VATRateClientHandlers : global::Sungero.CoreEntities.DatabookEntryClientHandlers
  {
    private global::Sungero.Commons.IVATRate _obj
    {
      get { return (global::Sungero.Commons.IVATRate)this.Entity; }
    }

    public virtual void NameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }



    public virtual void SidValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public VATRateClientHandlers(global::Sungero.Commons.IVATRate entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// VATRateClientFunctions.g.cs
// ==================================================================

namespace Sungero.Commons.Client
{
  public partial class VATRateFunctions : global::Sungero.CoreEntities.Client.DatabookEntryFunctions
  {
    private global::Sungero.Commons.IVATRate _obj
    {
      get { return (global::Sungero.Commons.IVATRate)this.Entity; }
    }

    public VATRateFunctions(global::Sungero.Commons.IVATRate entity) : base(entity) { }
  }
}

// ==================================================================
// VATRateFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Functions
{
  internal static class VATRate
  {
  }
}

// ==================================================================
// VATRateClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class VATRateClientPublicFunctions : global::Sungero.Commons.Client.IVATRateClientPublicFunctions
  {
  }
}

// ==================================================================
// VATRateActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public partial class VATRateActions : global::Sungero.CoreEntities.Client.DatabookEntryActions
  {
    private global::Sungero.Commons.IVATRate _obj { get { return (global::Sungero.Commons.IVATRate)this.Entity; } }
    public VATRateActions(global::Sungero.Commons.IVATRate entity) : base(entity) { }
  }

  public partial class VATRateCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Commons.IVATRate> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Commons.IVATRate>(this.Entities); }
    }
  }

  public partial class VATRateCollectionBulkActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int32> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class VATRateAnyChildEntityActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityActions
  {
  }

  public partial class VATRateAnyChildEntityCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityCollectionActions
  {
  }



}
