
// ==================================================================
// AcquaintanceTaskAddedAddenda.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Server
{


  public class AcquaintanceTaskAddedAddenda :
    global::Sungero.Domain.ChildEntity, global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddenda
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("857a524b-bcd9-42ff-998e-58a8ac8e7a07");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.RecordManagement.Server.AcquaintanceTaskAddedAddenda.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.RecordManagement.IAcquaintanceTaskAddedAddenda, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaState State
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskAddedAddendaState(this);
    }

    public new virtual global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaInfo Info
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaInfo)base.Info; }
    }


    public global::Sungero.RecordManagement.IAcquaintanceTask AcquaintanceTask { get; set; }

    public override global::Sungero.Domain.Shared.IEntity RootEntity
    {
      get { return this.AcquaintanceTask; }
      set { this.AcquaintanceTask = (global::Sungero.RecordManagement.IAcquaintanceTask)value; }
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.RecordManagement.AcquaintanceTaskAddedAddendaSharedHandlers(this);
    }

    private global::System.Int32? _AddendumId;
    public virtual global::System.Int32? AddendumId
    {
      get
      {
        return this._AddendumId;
      }

      set
      {
        this.SetPropertyValue("AddendumId", this._AddendumId, value, (propertyValue) => { this._AddendumId = propertyValue; }, this.AddendumIdChangedHandler);
      }
    }










    #region Framework events

    protected void AddendumIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.AddendumId, this.AddendumId, this);
     ((global::Sungero.RecordManagement.IAcquaintanceTaskAddedAddendaSharedHandlers)this.SharedHandlers).AddedAddendaAddendumIdChanged(args);
    }



    #endregion


    public AcquaintanceTaskAddedAddenda()
    {
    }

  }
}

// ==================================================================
// AcquaintanceTaskAddedAddendaHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement
{

}

// ==================================================================
// AcquaintanceTaskAddedAddendaEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Server
{
}
